// Keeps the screenshots honest.
//
//   npm run screens:check   checks screens.json against the files, the code
//                           and the README, and fails if anything is off
//   npm run screens:readme  rewrites the Screenshots section of the README
//                           from screens.json
//
// Plain Node, no packages. See src/assets/screens/README.md.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(root, "src/assets/screens");
const readmePath = path.join(root, "../README.md");
const data = JSON.parse(
  fs.readFileSync(path.join(dir, "screens.json"), "utf8"),
);

const START =
  "<!-- screens:start (generated by npm run screens:readme in web, do not edit by hand) -->";
const END = "<!-- screens:end -->";

const screens = new Map();
for (const section of data.sections) {
  for (const screen of section.screens) {
    screens.set(`${section.id}/${screen.id}`, { ...screen, section });
  }
}

// Width and height of a WebP file, read from its header.
function webpSize(file) {
  const b = fs.readFileSync(file);
  if (
    b.toString("ascii", 0, 4) !== "RIFF" ||
    b.toString("ascii", 8, 12) !== "WEBP"
  ) {
    throw new Error("not a WebP file");
  }
  const kind = b.toString("ascii", 12, 16);
  if (kind === "VP8 ")
    return {
      width: b.readUInt16LE(26) & 0x3fff,
      height: b.readUInt16LE(28) & 0x3fff,
    };
  if (kind === "VP8L") {
    const bits = b.readUInt32LE(21);
    return { width: (bits & 0x3fff) + 1, height: ((bits >> 14) & 0x3fff) + 1 };
  }
  if (kind === "VP8X")
    return { width: b.readUIntLE(24, 3) + 1, height: b.readUIntLE(27, 3) + 1 };
  throw new Error(`unknown WebP type ${kind}`);
}

// ---- README -------------------------------------------------------------

function imageCell(key, width) {
  const screen = screens.get(key);
  const file = `web/src/assets/screens/${screen.section.id}/${screen.file}.light.webp`;
  return `    <td width="${width}%" align="center" valign="top">\n      <b>${screen.title}</b><br><br>\n      <img src="${file}" alt="${screen.alt}" width="100%">\n    </td>`;
}

function buildReadmeBlock() {
  const lines = [START, "", "## Screenshots", ""];
  lines.push(
    'Everything below is from a demo organization called Sunshine, so none of it is real data. Each picture also has a dark version, and the live site shows more of every page in its product tour and "How to use" guide.',
    "",
  );
  for (const block of data.readme) {
    const keys = data.placements[block.placement];
    const width = Math.floor(100 / block.columns);
    lines.push(`### ${block.heading}`, "", block.text, "", "<table>");
    for (let i = 0; i < keys.length; i += block.columns) {
      lines.push("  <tr>");
      for (const key of keys.slice(i, i + block.columns))
        lines.push(imageCell(key, width));
      lines.push("  </tr>");
    }
    lines.push("</table>", "");
  }
  lines.push(END);
  return lines.join("\n");
}

function currentReadmeBlock(text) {
  const start = text.indexOf("<!-- screens:start");
  const end = text.indexOf(END);
  if (start === -1 || end === -1) return null;
  return { start, end: end + END.length };
}

// ---- Checks -------------------------------------------------------------

function check() {
  const problems = [];
  const seen = new Set();

  for (const section of data.sections) {
    const size = data.sizes[section.size];
    if (!size)
      problems.push(`Section ${section.id}: unknown size "${section.size}"`);
    section.screens.forEach((screen, index) => {
      const key = `${section.id}/${screen.id}`;
      const number = String(index + 1).padStart(2, "0");
      if (!screen.file.startsWith(`${number}-`)) {
        problems.push(
          `${key}: file "${screen.file}" should start with ${number}- to match its place in the list`,
        );
      }
      for (const field of ["title", "caption", "alt"]) {
        if (!screen[field]?.trim()) problems.push(`${key}: ${field} is empty`);
      }
      for (const theme of ["light", "dark"]) {
        const rel = `${section.id}/${screen.file}.${theme}.webp`;
        seen.add(rel);
        const file = path.join(dir, rel);
        if (!fs.existsSync(file)) {
          problems.push(`Missing file: ${rel}`);
          return;
        }
        try {
          const got = webpSize(file);
          if (
            size &&
            (got.width !== size.width || got.height !== size.height)
          ) {
            problems.push(
              `${rel} is ${got.width}x${got.height}, expected ${size.width}x${size.height}`,
            );
          }
        } catch (error) {
          problems.push(`${rel}: ${error.message}`);
        }
      }
    });
  }

  // Files nobody lists.
  for (const section of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!section.isDirectory()) continue;
    for (const name of fs.readdirSync(path.join(dir, section.name))) {
      if (!seen.has(`${section.name}/${name}`))
        problems.push(`Not listed in screens.json: ${section.name}/${name}`);
    }
  }

  // Placements point at real screenshots, and every screenshot is shown somewhere.
  const placed = new Set();
  for (const [name, keys] of Object.entries(data.placements)) {
    for (const key of keys) {
      placed.add(key);
      if (!screens.has(key))
        problems.push(`Placement ${name} lists unknown screenshot ${key}`);
    }
  }
  for (const key of screens.keys()) {
    if (!placed.has(key)) problems.push(`${key} is not used in any placement`);
  }

  // Placements named in the code exist, and placements in the file are used.
  const used = new Set();
  const walk = (folder) => {
    for (const entry of fs.readdirSync(folder, { withFileTypes: true })) {
      const full = path.join(folder, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.(tsx?|jsx?)$/.test(entry.name)) {
        const source = fs.readFileSync(full, "utf8");
        for (const match of source.matchAll(/placement\(\s*"([^"]+)"\s*\)/g))
          used.add(match[1]);
      }
    }
  };
  walk(path.join(root, "src"));
  for (const name of used) {
    if (!data.placements[name])
      problems.push(
        `The code uses placement "${name}", which is not in screens.json`,
      );
  }
  for (const name of Object.keys(data.placements)) {
    if (!name.startsWith("readme.") && !used.has(name))
      problems.push(
        `Placement "${name}" is in screens.json but no code uses it`,
      );
  }
  for (const block of data.readme) {
    if (!data.placements[block.placement])
      problems.push(
        `README block "${block.heading}" uses unknown placement ${block.placement}`,
      );
  }

  // The README matches what the list would generate.
  const text = fs.readFileSync(readmePath, "utf8");
  const range = currentReadmeBlock(text);
  if (!range)
    problems.push(
      "README has no screenshots block. Run npm run screens:readme.",
    );
  else if (text.slice(range.start, range.end) !== buildReadmeBlock()) {
    problems.push(
      "README screenshots are out of date. Run npm run screens:readme.",
    );
  }

  if (problems.length) {
    console.error(`Screenshot check found ${problems.length} problem(s):`);
    for (const problem of problems) console.error(`  - ${problem}`);
    process.exit(1);
  }
  console.log(
    `Screenshots OK: ${screens.size} screens, ${screens.size * 2} files, ${Object.keys(data.placements).length} placements.`,
  );
}

function writeReadme() {
  const text = fs.readFileSync(readmePath, "utf8");
  const block = buildReadmeBlock();
  const range = currentReadmeBlock(text);
  let next;
  if (range) {
    next = text.slice(0, range.start) + block + text.slice(range.end);
  } else {
    // First time: replace the old hand-written section.
    const from = text.indexOf("## Screenshots");
    const to = text.indexOf("## Why I Built This");
    if (from === -1 || to === -1)
      throw new Error("Could not find the Screenshots section in the README");
    next = text.slice(0, from) + block + "\n\n" + text.slice(to);
  }
  fs.writeFileSync(readmePath, next);
  console.log("README screenshots updated.");
}

const command = process.argv[2];
if (command === "check") check();
else if (command === "readme") writeReadme();
else {
  console.error("Usage: node scripts/screens.mjs check | readme");
  process.exit(1);
}
